<a href="https://colab.research.google.com/github/mchronowski/KISDPythonCourse/blob/main/Random_PESEL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Code for PESEL Random generator below. 
What works? Generating n-number of PESELs. All months have correct number of days. Code covers birth years from 1800-2099. PESEL numbers should be unique thanks to the "np.unique" but i don't know yet why this change pesel numbers**

---



In [1]:
import numpy as np
import random

x = np.random.randint(low=1, high=100000, size=10000000)

n = 40000000
year = np.random.randint(low=00, high=99, size=n)

month1 = np.random.randint(low=1, high=12, size=n)
month2 = np.random.randint(low=1, high=12, size=n) + 20 #for year >= 2000
month3 = np.random.randint(low=1, high=12, size=n) + 80 #for year 1899-1800
month_all = np.append(month1, month2)
month_all2 = np.append(month_all, month3)
#month = month1 + month2 + month3 to n=40000000
month_alt = random.choices(month_all2, k=n)
month = np.array(month_alt)

#31 days (1, 3, 5, 7, 8, 10, 12) / +20 (21, 23, 25, 27, 28, 30, 32)  / +80 (81, 83, 85, 87, 88, 90, 92)
odd_months = (1, 3, 5, 7, 8, 10, 12, 21, 23, 25, 27, 28, 30, 32, 81, 83, 85, 87, 88, 90, 92)

#30 days (4, 6, 9, 11) / +20 (24, 26, 29, 31) / +80 (84, 86, 89, 91)
even_months = (4, 6, 9, 11, 24, 26, 29, 31, 84, 86, 89, 91)

if np.any(month) in odd_months:
        day = np.random.randint(low=1, high=31, size=n)
elif np.any(month) in even_months:
        day = np.random.randint(low=1, high=30, size=n)

#feb 28/29 daysif month
else: 
        if year % 4 == 0:
                day = random.randint(1,29)
        else:
                day = random.randint(1,28)


ser_1 = np.random.randint(low=0, high=9, size=n)
ser_2 = np.random.randint(low=0, high=9, size=n)
ser_3 = np.random.randint(low=0, high=9, size=n)
sex = np.random.randint(low=0, high=9, size=n)

# checksum
control = (year//10) + 3*(year%10)
control += 7*(month//10) + 9*(month%10)
control += (day//10) + 3*(day%10)
control += 7*(ser_1//10) + 9*(ser_1%10)
control += (ser_2//10) + 3*(ser_2%10)
control += 7*(ser_3//10) + 9*(ser_3%10)
control += (sex//10) + 3*(sex%10)

control = (10 - (control % 10)) % 10

pesel_db = 1000000000*year + 10000000*month + 100000*day + 10000*ser_1 + 1000*ser_2 + 100*ser_3 + 10 * sex + control

#To remove duplicates there is uni_pesel list
uni_pesel = np.unique(pesel_db)

In [2]:
#TEST PESEL
pesel_db

array([96900532730, 71860104803,  2081251773, ..., 84840538475,
       95891970868, 95273042066])

In [3]:
month[3], day[3]

(5, 28)

In [4]:
#TEST Unique Pesel
uni_pesel[2]

10100868

**Analyizing vibration of PESEL number. Code works in 3 steps.**



---



In [5]:
#1st sum
def getSum(n):  
     
    sum = 0
    while np.any((n != 0)):  
        
        sum = sum + (n % 10) 
        n = n//10
        
    return sum
    
n = np.array(pesel_db)
print(getSum(n))

[44 38 36 ... 56 70 44]


In [6]:
#2nd sum
def getSum(n2):  
     
    sum = 0
    while np.any((n2 != 0)):  
        
        sum = sum + (n2 % 10) 
        n2 = n2//10
        
    return sum
    
n2 = np.array(getSum(n))
print(getSum(n2))

[ 8 11  9 ... 11  7  8]


In [7]:
#3rd sum
def getSum(n3):  
     
    sum = 0
    while np.any((n3 != 0)):  
        
        sum = sum + (n3 % 10) 
        n3 = n3//10
        
    return sum
    
n3 = np.array(getSum(n2))
print('Vibrations for a generated PESEL', getSum(n3))

Vibrations for a generated PESEL [8 2 9 ... 2 7 8]


In [8]:
#TEST Vibartion for a choosen PESEL
getSum(n3)[1]

2

In [ ]:
#Different approach. Not finished. No idea how to get 2nd, 3rd [...] number with rounding number with so many digits. 
#I found a command "sum" in python library and decide to use it instead. Code above is working as it should i guess.
import math as mt
num1 = np.floor(pesel_db / 10000000000)
num1

array([9., 6., 9., ..., 7., 8., 0.])

**Analayzing data from PESEL dataset. Number of Female and Male Pesels. How many ppl are birth 29th february**

---



In [15]:
#According to Wikipedia:
# PESEL number has the form of YYMMDDZZZXQ
# YYMMDD is the date of birth (with century encoded in month field)
# ZZZX is the personal identification number
# X codes sex (even number for females, odd number for males)
# Q is a check digit


#Checking number of male and females in our database
import numpy as np
mylist = np.array(pesel_db)

def get_matches(mylist, start, end, valuelist):
    valuelist = [str(value) for value in valuelist]
    return [str(i)[start:end+1] in valuelist  for i in mylist]
storage = get_matches(mylist, start=9, end=9, valuelist=[0,2,4,6,8]).count(True)

print("Number of Female PESELs:", storage)
print("Number of Male PESELs", 40000000-storage)


Number of Female PESELs: 21799894
Number of Male PESELs 18200106


In [14]:
#Checking number of ppl birth in 29 february.
#Possible MMDD "0229 2229 8229"

import numpy as np
mylist = np.array(pesel_db)

def get_matches(mylist, start, end, valuelist):
    valuelist = [str(value) for value in valuelist]
    return [str(i)[start:end+1] in valuelist  for i in mylist]
storage2 = get_matches(mylist, start=2, end=5, valuelist=[229, 2229, 8229]).count(True)

print("People birth in 29th February in database:", storage2)


People birth in 29th February in database: 72538
